version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

executors:
  my-custom-executor:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/ParkIlHoon/data-collector/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build-jar:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          ./gradlew test
          ./gradlew build
      - codecov/upload

workflows:
  my-custom-workflow:
    jobs:
      - build-jar